apiVersion: v1
kind: ConfigMap
metadata:
  name: ${RUN_NAME}-env
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/managed-by: osdu_perf
    osdu-perf.io/run-id: ${RUN_NAME}
data:
  LOCUST_HOST: "${LOCUST_HOST}"
  LOCUST_USERS: "${LOCUST_USERS}"
  LOCUST_SPAWN_RATE: "${LOCUST_SPAWN_RATE}"
  LOCUST_RUN_TIME: "${LOCUST_RUN_TIME}"
  LOCUST_EXPECT_WORKERS: "${LOCUST_EXPECT_WORKERS}"
  PARTITION: "${PARTITION}"
  APPID: "${APPID}"
  AZURE_LOAD_TEST: "true"
  OSDU_PERF_ENV: "AKS"
  TEST_SCENARIO: "${SCENARIO}"
  OSDU_PERF_PROFILE_NAME: "${PROFILE_NAME}"
  OSDU_PERF_PROFILE_USERS: "${LOCUST_USERS}"
  OSDU_PERF_PROFILE_SPAWN_RATE: "${LOCUST_SPAWN_RATE}"
  OSDU_PERF_PROFILE_RUN_TIME: "${LOCUST_RUN_TIME}"
  OSDU_PERF_PROFILE_ENGINES: "${ENGINE_INSTANCES}"
  OSDU_PERF_TEST_NAME: "${TEST_NAME}"
  OSDU_PERF_TEST_RUN_ID: "${RUN_NAME}"
  WEB_UI: "${WEB_UI}"
  OSDU_PERF_AZURE_CONFIG: "${AZURE_CONFIG_PATH}"
