apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "osdu-perf.name" . }}-env
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "osdu-perf.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
