{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "osdu-perf.labels" . | nindent 4 }}
  annotations:
    azure.workload.identity/client-id: "{{ required "serviceAccount.workloadIdentityClientId is required when serviceAccount.create=true" .Values.serviceAccount.workloadIdentityClientId }}"
{{- end }}
